In [1]:
from model import *
from utils import *
import pandas as pd
import pickle

C:\Users\sicom\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
df = pd.read_csv("../processed/val.csv")
labels = df['diacritics'].apply(eval)
data = df["word_with_context"].apply(lambda x: eval(x))

print("Data loaded")

test_data = load_train_data(data, labels)

print("Data processed")

# Train model


# train_letter_model(tashkeel_model, train_data, n_classes=15, epochs=10)


Data loaded
Data processed


c:\University\NLP\project\code\dataset.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.x = torch.tensor(x)
c:\University\NLP\project\code\dataset.py:17: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.e = torch.tensor(e)
c:\University\NLP\project\code\dataset.py:18: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  self.y = torch.tensor(y)


In [3]:
tashkeel_model = pickle.load(open("./../models/tashkeel_model_context_5epochs.pkl", "rb"))

eval_letter_model(tashkeel_model, test_data, 200)

100%|██████████| 529/529 [00:20<00:00, 26.29it/s]


Test Accuracy: 0.11557379447313756


In [7]:
predicted = pred_letter_model(tashkeel_model, test_data)

  0%|          | 0/105646 [00:00<?, ?it/s]

100%|██████████| 105646/105646 [02:32<00:00, 692.42it/s]


In [10]:
len(predicted)
predicted[0:10]

[tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([14,  6,  0,  0,  0,  0,  0,  0,  0,  0,  0], device='cuda:0'),
 tensor([4, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([ 0, 14,  0,  0,  0,  0,  0,  0,  0,  0,  0], device='cuda:0'),
 tensor([0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0'),
 tensor([0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0], device='cuda:0')]

In [1]:
import pandas as pd



In [3]:
df = pd.read_csv("../processed/val.csv")
df.head()

0   
0              قَوْلُهُ وَلَا تُكْرَهُ ضِيَافَتُهُ .  \
1  الْفَرْقُ الثَّالِثُ وَالثَّلَاثُونَ بَيْنَ قَ...   
2  قَوْلُهُ وَهُوَ أَيْ الْبَيْعُ بِالْمَعْنَى ال...   
3  إذْ الْمُقَابَلَةُ لَا تَصْدُقُ عَلَى الْعَقْد...   
4  وَقَدْ يُجْعَلُ كَلَامُهُ عَلَى حَذْفِ مُضَافٍ...   

                                           tokenized   
0   ['قَوْلُهُ', 'وَلَا', 'تُكْرَهُ', 'ضِيَافَتُهُ']  \
1  ['الْفَرْقُ', 'الثَّالِثُ', 'وَالثَّلَاثُونَ',...   
2  ['قَوْلُهُ', 'وَهُوَ', 'أَيْ', 'الْبَيْعُ', 'ب...   
3  ['إذْ', 'الْمُقَابَلَةُ', 'لَا', 'تَصْدُقُ', '...   
4  ['وَقَدْ', 'يُجْعَلُ', 'كَلَامُهُ', 'عَلَى', '...   

                                   tokenized_cleaned   
0                  ['قوله', 'ولا', 'تكره', 'ضيافته']  \
1  ['الفرق', 'الثالث', 'والثلاثون', 'بين', 'قاعدة...   
2  ['قوله', 'وهو', 'أي', 'البيع', 'بالمعنى', 'الث...   
3  ['إذ', 'المقابلة', 'لا', 'تصدق', 'على', 'العقد...   
4  ['وقد', 'يجعل', 'كلامه', 'على', 'حذف', 'مضاف',...   

                                             cleaned   
0                قَوْلُهُ وَلَا تُكْرَهُ ضِيَافَتُهُ  \
1  الْفَرْقُ الثَّالِثُ وَالثَّلَاثُونَ بَيْنَ قَ...   
2  قَوْلُهُ وَهُوَ أَيْ الْبَيْعُ بِالْمَعْنَى ال...   
3  إذْ الْمُقَابَلَةُ لَا تَصْدُقُ عَلَى الْعَقْد...   
4  وَقَدْ يُجْعَلُ كَلَامُهُ عَلَى حَذْفِ مُضَافٍ...   

                                          diacritics   
0  [[0, 6, 2, 2], [0, 0, 14], [2, 6, 0, 2], [4, 0...  \
1  [[14, 6, 0, 6, 2], [14, 14, 8, 14, 4, 2], [0, ...   
2  [[0, 6, 2, 2], [0, 2, 0], [0, 6], [14, 6, 0, 6...   
3  [[14, 6], [14, 6, 2, 0, 14, 0, 0, 2], [0, 14],...   
4  [[0, 0, 6], [2, 6, 0, 2], [0, 0, 14, 2, 2], [0...   

                                       prob_per_char   
0  [[[0.6011768551814318, 0.008908139915004904, 0...  \
1  [[[0.0023798288985085038, 0.0, 0.0019489978048...   
2  [[[0.6011768551814318, 0.008908139915004904, 0...   
3  [[[0.0, 0.0, 0.0, 0.0, 0.5149124494900904, 0.0...   
4  [[[0.5603507962150934, 0.0005000384644972691, ...   

                                           bef_after   
0  [[[36, 21], [3, 16], [21, 0], [16, 36]], [[36,...  \
1  [[[36, 16], [25, 29], [16, 18], [29, 3], [18, ...   
2  [[[36, 21], [3, 16], [21, 0], [16, 36]], [[36,...   
3  [[[36, 26], [7, 36]], [[36, 16], [25, 24], [16...   
4  [[[36, 3], [21, 35], [3, 36]], [[36, 6], [17, ...   

                                            features  
0  [[[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0...  
1  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...  
2  [[[0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0...  
3  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0...  
4  [[[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0...

In [4]:
hi = df["diacritics"]
hi.head()

0    [[0, 6, 2, 2], [0, 0, 14], [2, 6, 0, 2], [4, 0...
1    [[14, 6, 0, 6, 2], [14, 14, 8, 14, 4, 2], [0, ...
2    [[0, 6, 2, 2], [0, 2, 0], [0, 6], [14, 6, 0, 6...
3    [[14, 6], [14, 6, 2, 0, 14, 0, 0, 2], [0, 14],...
4    [[0, 0, 6], [2, 6, 0, 2], [0, 0, 14, 2, 2], [0...
Name: diacritics, dtype: object

In [6]:
hi.explode().to_list()

['[[0, 6, 2, 2], [0, 0, 14], [2, 6, 0, 2], [4, 0, 14, 0, 2, 2]]',
 '[[14, 6, 0, 6, 2], [14, 14, 8, 14, 4, 2], [0, 14, 14, 8, 0, 14, 2, 14, 0], [0, 6, 0], [0, 14, 4, 0, 4], [0, 0, 10, 4], [14, 6, 2, 6, 4], [0, 0, 14], [0, 0, 4, 4], [2, 14, 0], [0, 6, 4, 4], [0, 6], [0, 6, 4, 4], [2, 14, 0], [0, 0, 4, 4], [0, 0, 6, 0], [0, 14, 4, 0, 4], [0, 0, 10, 4, 4], [0, 0, 14], [14, 14, 8, 0, 4], [0, 14, 14, 8, 6, 4], [0, 4, 14, 1, 14], [0, 0, 6, 4, 14, 2, 2], [0, 8], [14, 6, 2, 6, 0], [14, 6], [0, 14, 0], [0, 2], [0, 0, 3], [4, 0, 6, 4], [0, 6, 5], [0, 0, 0, 8, 0], [0, 0, 6, 4], [0, 14], [2, 6, 0, 0, 2], [0, 6], [0, 14, 0], [0, 2], [0, 0, 0, 14, 4], [0, 6], [0, 6, 0, 14, 3], [0, 0, 0, 8, 0], [0, 0, 14], [0, 4, 14, 4, 0, 14], [0, 6], [2, 6, 0, 0, 6], [0, 6], [0, 0, 14], [0, 6, 4, 0, 14], [2, 14, 0], [0, 6, 5], [2, 6, 2, 4, 0], [4, 0, 14, 1], [0, 0, 14], [0, 0, 4], [14, 6, 0, 14, 12], [0, 0, 14], [0, 2, 10], [4, 6, 0, 14, 2], [0, 4, 8, 4], [14, 6, 0, 6, 0, 14, 4], [0, 4, 8], [0, 6, 0], [14, 14, 8, 0,